In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import pickle
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC

In [3]:
data = pd.read_csv("dataset.csv")

In [4]:
data.head()

Latitude  Longitude  Depth  Magnitude
0     29.06      77.42    5.0        2.5
1     19.93      72.92    5.0        2.4
2     31.50      74.37   33.0        3.4
3     28.34      76.23    5.0        3.1
4     27.09      89.97   10.0        2.1

In [5]:
data = np.array(data)
print(data)

[[29.06 77.42  5.    2.5 ]
 [19.93 72.92  5.    2.4 ]
 [31.5  74.37 33.    3.4 ]
 ...
 [22.5  88.1  10.    3.6 ]
 [24.6  94.2  54.    3.5 ]
 [14.5  92.9  10.    4.6 ]]


In [7]:
X = data[:, 0:-1]
y = data[:, -1]
y = y.astype('int')
X = X.astype('int')

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

print(X_train,y_train)


[[ 22  94  10]
 [ 27  75   5]
 [ 34  76  10]
 ...
 [ 31  76   5]
 [ 23  70  10]
 [ 37  72 125]] [4 2 2 ... 3 4 4]


In [13]:
Random_forest_classifier = RandomForestClassifier()#creating the model

Random_forest_classifier.fit(X_train, y_train)#fitting the model with training dataset
y_pred = Random_forest_classifier.predict(X_test)#predicting the result using test set
 
print(metrics.accuracy_score(y_test, y_pred))#printing the accuracy score

0.5735294117647058


In [19]:
#importing the descision tree classifier from the sklearn tree 
tree = GradientBoostingClassifier() #making an instance the descision tree with maxdepth = 3 as passing the input
clf = tree.fit(X_train,y_train) #here we are passing our training and the testing data to the tree and fitting it

y_pred = clf.predict(X_test) #predicting the value by passing the x_test datset to the tree 
print(metrics.accuracy_score(y_test, y_pred))# here we are printing the accuracy score of the prediction and the testing data

0.5827205882352942


In [22]:
#importing the descision tree classifier from the sklearn tree 
tree = SVC(gamma='auto') #making an instance the support vector tree
clf = tree.fit(X_train,y_train) #here we are passing our training and the testing data to the tree and fitting it
y_pred = clf.predict(X_test) #predicting the value by passing the x_test datset to the tree 
print(metrics.accuracy_score(y_test, y_pred))# here we are printing the accuracy score of the prediction and the testing data

0.5680147058823529
